version: '3.8'
services:
  node:
    restart: always
    build: .
    ports : 
      - 5000:5000
    links : 
      - mongo
    volumes:
      - ./:/code
  
  mongo : 
    image : mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/derash-android
volumes:
 mongodb: