
name: derash
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1
  uuid: ^3.0.6
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.1.58+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
    

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
